# Actionsを使い始めるための基本的なワークフローです

name: CI

# ワークフローの実行条件を制御します
on:
  # "main"ブランチに対するプッシュやプルリクエストのイベントでワークフローをトリガーします
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Actionsタブから手動でこのワークフローを実行できるようにします
  workflow_dispatch:

# ワークフローの実行は、1つ以上のジョブで構成され、順次または並列で実行されます
jobs:
  # このワークフローには "build" という単一のジョブが含まれています
  build:
    # ジョブを実行するランナーのタイプを指定します
    runs-on: ubuntu-latest

    # ステップはジョブの一部として実行される一連のタスクを表します
    steps:
      # リポジトリを$GITHUB_WORKSPACEにチェックアウトし、ジョブがアクセスできるようにします
      - uses: actions/checkout@v4

      # ランナーのシェルを使って単一のコマンドを実行します
      - name: ワンラインスクリプトを実行
        run: echo Hello, world!

      # ランナーのシェルを使って複数行のコマンドを実行します
      - name: 複数行のスクリプトを実行
        run: |
          echo 他のアクションを追加してビルドし、
          echo テストおよびデプロイを行ってください。
